### ISSUE TITLE
wrong kernel

### ISSUE THREAD

**Issue by TonyStark** [mohancm100/android_kernel_coolpad_msm8994#1]
this is 8952 kernel, and note 5 build on 8952 kernel not on 8994
ref: /arch/arm/boot/dts/qcom/Makefile
(https://github.com/mohancm/android_kernel_coolpad_msm8994/blob/66e9d48677f0aebc408f08d4b87e5b0d43aaaf85/arch/arm/boot/dts/qcom/Makefile)
Note 5:
Model: CP3600I
SnapDragon: 617

**Comment by mohancm** [comment]
check orignal defconfig
this kernel uses board msm8994

**Comment by TonyStark** [comment]
see this >> https://github.com/mohancm/android_kernel_coolpad_msm8994/blob/66e9d48677f0aebc408f08d4b87e5b0d43aaaf85/arch/arm/boot/dts/qcom/Makefile

**Comment by mohancm** [comment]
whatever

**Comment by Shreedhan003** [comment]
i compiled need tester
